[image-optimization]
enabled  = true
quality  = 95
max-size = 1500

[pandoc]
args = [
    "--pdf-engine=xelatex",                                     # использовать XeLaTeX как PDF-движок
    "--template=templates/referat.tex", # шаблон для оформления документа
    "--lua-filter=filters/center-images.lua",                   # фильтр для центрирования изображений
    "--lua-filter=filters/word-count.lua",                      # фильтр для подсчёта слов в документе
    "--lua-filter=filters/replace-image-path.lua",              # фильтр для корректной вставки изображений, если включен image-optimization.
    "--metadata-file=tmp/metadata.yaml",                        # файл с метаданными
    "--citeproc",                                             # включить обработку цитирований, нужно указать bibliography
    "--csl=gost-numeric.csl"
]
src = ["*"]
out-name = "output.pdf"

[metadata.general]
title = "Реферат на тему:"
subtitle = "История развития интеллектуальных систем в авиации"
# abstract = ""
author = ["Баранов А. Т."]
date = "2024"
lang = "ru"
link-citations = true

[metadata.layout]
documentclass = "scrartcl"    
classoption = "russian"                                                # параметр класса документа(scrartcl, scrbook или scrreprt), если book или report(scrbook или scrreport), то включить параметр book 
geometry = "left=30mm, right=10mm, top=20mm, bottom=20mm, footskip=0cm"          # поля страницы
indent = true                                                                # отступы в абзацах
linestretch = 1.5                                                            # межстрочный интервал

# pagestyle = "plain"     # стиль страницы (plain, headings, empty для article). связано с колонтитулами
papersize = "a4"          # размер бумаги (a4, letter, ...)

[metadata.fonts]
# fontfamily = "libertinus"        # семейство шрифтов для использования с pdflatex
# fontfamilyoptions = "osf, p, sc" # опции fontfamily
fontsize = "12pt"                  # размер шрифта для body text

mainfont = "Times New Roman"                   #
sansfont = "Times New Roman"                   #
monofont = "Times New Roman"                  #  семейства шрифтов для использования 
mathfont = "Times New Roman"                   #  с xelatex или lualatex

# mainfontoptions = "BoldFont={Times New Roman Bold}"           #
# sansfontoptions = "..."           #
# monofontoptions = "..."           #  
# mathfontoptions = "..."           # опции шрифтов


[metadata.links]
colorlinks = true        # добавить цвет к тексту ссылки; автоматически включается, если установлено любое из значений linkcolor, filecolor, citecolor, urlcolor или toccolor
# boxlinks = true        # добавить рамку к ссылкам (нет эффекта если colorlinks = true) 
linkcolor = "NavyBlue"   # цвет внутренних ссылок
filecolor = "magenta"    # цвет ссылок на файлы
citecolor = "violet"     # цвет ссылок на источники
urlcolor = "cyan"        # цвет ссылок на URL
toccolor = "black"       # цвет ссылок в оглавлении
links-as-notes = false   # отображать ссылки как сноски
urlstyle = "same"        # стиль ссылок на URL (same, tt, rm, sf)

[metadata.frontmatter]
toc = true               # включить оглавление
toc-depth = 3            # глубина оглавления

[metadata.bibliography]
#biblatexoptions = ["backend=biber", "style=gost-numeric", "sorting=none"]               # опции для пакета biblatex
# biblio-style = "alphabetic"        # стиль библиографии
biblio-title = "Список литературы" # заголовок библиографии
bibliography = "bibliography.bib"    # путь к файлу библиографии
# natbiboptions = []                 # опции для пакета natbib

[metadata.template.titlepage]
titlepage = true                            # включить титульную страницу
titlepage-text-color = "000000"             # цвет текста на титульной странице
titlepage-rule-height = -1                  # высота линии на титульной странице
titlepage-logo = "logo.png"                # логотип для титульной страницы
logo-width = "35.6mm"                         # ширина логотипа

[metadata.template.toc]
toc-own-page = true                         # оглавление на отдельной странице



[metadata.template.caption]
caption-justification = "centering"         # выравнивание подписей к рисункам или таблицам по центру
caption-color = "000000"                    # цвет подписей

[metadata.template.footnotes]
footnotes-pretty = true                     # настройка сносок
# footnotes-disable-backlinks = true        # отключение обратных ссылок в сносках

[metadata.template.headerandfooter]
# disable-header-and-footer = true          # отключение колонтитулов

[metadata.template.header]
header-left = '\ '    # левый верхний колонтитул: номер страницы
header-center = '\ '          # центральный верхний колонтитул: пустой
header-right = '\ ' # правый верхний колонтитул: текущий раздел

[metadata.template.footer]
footer-left = '\ '            # левый нижний колонтитул: пустой
footer-center = '\thepage'          # центральный нижний колонтитул: пустой
footer-right = '\ '           # правый нижний колонтитул: пустой

[metadata.latex]
header-includes = '''
header-includes: |
    \usepackage{indentfirst}
    \setcounter{page}{2}
    \setkomafont{section}{\fontsize{14}{16}\selectfont\bfseries}
    \setkomafont{subsection}{\fontsize{12}{14}\selectfont\bfseries}
    \setkomafont{subsubsection}{\fontsize{12}{14}\selectfont\bfseries}
''' 



[metadata.fonts.babelfonts]

[metadata.template.page-background]

[metadata.template.figure]

[metadata.template.table]

[metadata.template.listings]

[metadata.template.book]